import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import cifar10
import pandas as pd

(X_train_org, Y_train), (X_test_org, Y_test) = cifar10.load_data()
Y_train = Y_train.reshape(Y_train.shape[0])
Y_test = Y_test.reshape(Y_test.shape[0])


models = [
    {
        "name": "2000 Clauses",
        "methods_params": [
            {
                "name": "AugmentedAdaptiveThresholdingMean",
                "clauses": "2000",
                "t": "500",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingMean",
                "clauses": "2000",
                "t": "500",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "ColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "2000",
                "t": "3000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "HistogramOfGradients",
                "clauses": "2000",
                "t": "50",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "AugmentedHistogramOfGradients",
                "clauses": "2000",
                "t": "50",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "Canny",
                "clauses": "2000",
                "t": "1500",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedCanny",
                "clauses": "2000",
                "t": "1500",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "OtsuThresholding",
                "clauses": "2000",
                "t": "3000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedOtsuThresholding",
                "clauses": "2000",
                "t": "3000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingGaussian",
                "clauses": "2000",
                "t": "2500",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveThresholdingGaussian",
                "clauses": "2000",
                "t": "2500",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
        ],
    },
    {
        "name": "4000 Clauses",
        "methods_params": [
            {
                "name": "AugmentedAdaptiveThresholdingMean",
                "clauses": "4000",
                "t": "1000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingMean",
                "clauses": "4000",
                "t": "1000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "ColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "4000",
                "t": "6000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "HistogramOfGradients",
                "clauses": "4000",
                "t": "100",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "AugmentedHistogramOfGradients",
                "clauses": "4000",
                "t": "100",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "Canny",
                "clauses": "4000",
                "t": "3000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedCanny",
                "clauses": "4000",
                "t": "3000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "OtsuThresholding",
                "clauses": "4000",
                "t": "6000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedOtsuThresholding",
                "clauses": "4000",
                "t": "6000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingGaussian",
                "clauses": "4000",
                "t": "5000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveThresholdingGaussian",
                "clauses": "4000",
                "t": "5000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
        ],
    },
    {
        "name": "8000 Clauses",
        "methods_params": [
            {
                "name": "AugmentedAdaptiveThresholdingMean",
                "clauses": "8000",
                "t": "2000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingMean",
                "clauses": "8000",
                "t": "2000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "ColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "8000",
                "t": "12000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "HistogramOfGradients",
                "clauses": "8000",
                "t": "200",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "AugmentedHistogramOfGradients",
                "clauses": "8000",
                "t": "200",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "Canny",
                "clauses": "8000",
                "t": "6000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedCanny",
                "clauses": "8000",
                "t": "6000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "OtsuThresholding",
                "clauses": "8000",
                "t": "12000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedOtsuThresholding",
                "clauses": "8000",
                "t": "12000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingGaussian",
                "clauses": "8000",
                "t": "10000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveThresholdingGaussian",
                "clauses": "8000",
                "t": "10000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
        ],
    },
    {
        "name": "16000 Clauses",
        "methods_params": [
            {
                "name": "AugmentedAdaptiveThresholdingMean",
                "clauses": "16000",
                "t": "4000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingMean",
                "clauses": "16000",
                "t": "4000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "ColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "16000",
                "t": "24000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "HistogramOfGradients",
                "clauses": "16000",
                "t": "400",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "AugmentedHistogramOfGradients",
                "clauses": "16000",
                "t": "400",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "Canny",
                "clauses": "16000",
                "t": "12000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedCanny",
                "clauses": "16000",
                "t": "12000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "OtsuThresholding",
                "clauses": "16000",
                "t": "24000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedOtsuThresholding",
                "clauses": "16000",
                "t": "24000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingGaussian",
                "clauses": "16000",
                "t": "20000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveThresholdingGaussian",
                "clauses": "16000",
                "t": "20000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
        ],
    },
    {
        "name": "32000 Clauses",
        "methods_params": [
            {
                "name": "AugmentedAdaptiveThresholdingMean",
                "clauses": "32000",
                "t": "8000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingMean",
                "clauses": "32000",
                "t": "8000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "ColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "32000",
                "t": "48000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "HistogramOfGradients",
                "clauses": "32000",
                "t": "800",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "AugmentedHistogramOfGradients",
                "clauses": "32000",
                "t": "800",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "Canny",
                "clauses": "32000",
                "t": "24000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedCanny",
                "clauses": "32000",
                "t": "24000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "OtsuThresholding",
                "clauses": "32000",
                "t": "48000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedOtsuThresholding",
                "clauses": "32000",
                "t": "48000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingGaussian",
                "clauses": "32000",
                "t": "40000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveThresholdingGaussian",
                "clauses": "32000",
                "t": "40000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
        ],
    },
    {
        "name": "64000 Clauses",
        "methods_params": [
            {
                "name": "AugmentedAdaptiveThresholdingMean",
                "clauses": "64000",
                "t": "16000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingMean",
                "clauses": "64000",
                "t": "16000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AdaptiveColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "ColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "ColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "3",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "4",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "AugmentedColorThermometers",
                "clauses": "64000",
                "t": "96000",
                "s": "5.0",
                "patch_dim": "5",
                "weighted": "1",
                "resolution": "8",
            },
            {
                "name": "HistogramOfGradients",
                "clauses": "64000",
                "t": "1600",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "AugmentedHistogramOfGradients",
                "clauses": "64000",
                "t": "1600",
                "s": "10.00",
                "patch_dim": "0",
                "weighted": "0",
            },
            {
                "name": "Canny",
                "clauses": "64000",
                "t": "48000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedCanny",
                "clauses": "64000",
                "t": "48000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "OtsuThresholding",
                "clauses": "64000",
                "t": "96000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AugmentedOtsuThresholding",
                "clauses": "64000",
                "t": "96000",
                "s": "10.0",
                "patch_dim": "10",
                "weighted": "1",
            },
            {
                "name": "AdaptiveThresholdingGaussian",
                "clauses": "64000",
                "t": "80000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
            {
                "name": "AugmentedAdaptiveThresholdingGaussian",
                "clauses": "64000",
                "t": "80000",
                "s": "3.5",
                "patch_dim": "5",
                "weighted": "1",
            },
        ],
    },
]


combined_accuracy_per_model = {}


def construct_filename(method, epoch):
    resolution = f"_{method['resolution']}" if "resolution" in method else ""
    return f"class_sums/CIFAR10{method['name']}_{epoch}_{method['clauses']}_{method['t']}_{method['s']}_{method['patch_dim']}{resolution}_32_{method['weighted']}.txt"


for model in models:
    model_name = model["name"]
    combined_accuracy_per_epoch = []

    for epoch in range(1, 251):
        scores_list = []

        for method in model["methods_params"]:
            filename = construct_filename(method, epoch)
            try:
                class_sums = np.loadtxt(filename, delimiter=",")
                scores_list.append(class_sums)
            except IOError:
                print(f"File {filename} not found.")
                continue

        if scores_list:
            votes = np.zeros_like(scores_list[0])
            for scores in scores_list:
                normalized_scores = scores / np.ptp(scores)
                votes += normalized_scores

            Y_test_predicted = votes.argmax(axis=1)
            accuracy = (Y_test_predicted == Y_test).mean()
            combined_accuracy_per_epoch.append(accuracy)

    combined_accuracy_per_model[model_name] = combined_accuracy_per_epoch


epochs = range(1, 251)
for model_name, accuracies in combined_accuracy_per_model.items():
    plt.plot(epochs, accuracies, label=model_name)
    print(accuracies)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.grid(True)
plt.legend()
plt.show()

data_for_csv = {"Model Name": list(combined_accuracy_per_model.keys())}
for i in range(1, 26):
    data_for_csv[f"Epoch {226 + i}"] = [
        accuracies[-25 + i - 1] for accuracies in combined_accuracy_per_model.values()
    ]

df = pd.DataFrame(data_for_csv)

csv_file_path = "model_accuracies_last_25_epochs.csv"
df.to_csv(csv_file_path, index=False)
print(f"Accuracies saved to {csv_file_path}")
